#!/usr/local/bin/perl

# Определяем переменную, содержащую путь к исходному файлу
$origfile = "guest.htm";
# Определяем переменную, содержащую путь к временному файлу
$newfile = "temp.htm";

&parse_form;

&empty unless $FORM{'name'};
&empty unless $FORM{'comment'};

open(INFILE, "<$origfile");
open(OUTFILE, ">$newfile");
while ($line = <INFILE>) {
  printf OUTFILE $line;
  if ($line =~ /<!-- begin content guestbook -->/i) {
    # Добавляем новые данные в файл:
    print OUTFILE "<TR><TD><HR COLOR=#000080 SIZE=1 WIDTH=290 ALIGN=LEFT></TD></TR>\n";
    print OUTFILE "<TR><TD>\n";
    print OUTFILE "<P CLASS=\"gb\">Имя:&nbsp;",$FORM{'name'},"\n";
    print OUTFILE "<P CLASS=\"gb\">E-mail:&nbsp;<A HREF=\"mailto:$FORM{'email'}\" CLASS=\"gb\">",$FORM{'email'},"</A>\n";
    print OUTFILE "<P CLASS=\"gb\">Домашняя страничка:&nbsp;<A HREF=\"$FORM{'homepage'}\" CLASS=\"gb\">",$FORM{'homepage'},"</A>\n";
    print OUTFILE "<P CLASS=\"gb\">Комментарий:\n<PRE>",$FORM{'comment'},"</PRE>\n";
    print OUTFILE "</TD></TR>\n";
  }
}
# Закрываем файлы
close(INFILE);
close(OUTFILE);
# Удаляем исходный файл и переименовываем новый в исходный
unlink($origfile);
rename($newfile, $origfile);

&add_top;
&add_middle;
&add_bottom;

#-----------------------
sub empty {
&add_top;
&add_middle;
&add_bottom;
exit;
}

sub parse_form {
	if ($ENV{'REQUEST_METHOD'} eq "POST") {$mode = 0}
	if ($mode == 0) {read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'})}
	@pairs = split(/&/, $buffer);
	foreach $pair (@pairs) {
		($name, $value) = split(/=/, $pair);
		$value =~ tr/+/ /;
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		$FORM{$name} = $value;
	}
}

sub add_top {
print "Content-Type: text/html\n\n";
print "<HTML><!-- generated by MandoR http://explode.to/mandor -->\n";
print "<HEAD>\n";
print "<meta charset=windows-1251>\n";
print "<TITLE>Гостевая книга - KEYBOARD ON-LINE</TITLE>\n";
print "<LINK HREF=\"../index.css\" REL=\"STYLESHEET\" TYPE=\"text/css\">\n";
print "</HEAD>\n";
print "<BODY BGCOLOR=#FFFFFF TEXT=#000000>\n";
print "<TABLE BGCOLOR=#000080 WIDTH=600 CELLPADDING=0 CELLSPACING=0 BORDER=0>\n";
print "<TR VALIGN=TOP>\n";
print "<TD>&nbsp;</TD>\n";
print "</TR>\n";
print "</TABLE>\n";
print "<!-- begin content -->\n";
print "<TABLE WIDTH=600 CELLPADDING=0 CELLSPACING=0 BORDER=0>\n";
print "<TR VALIGN=TOP>\n";
print "<!-- begin 1st column -->\n";
print "<TD WIDTH=150 BGCOLOR=#E6E6FF>\n";
print "<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=4 BORDER=0>\n";
print "<TR ALIGN=RIGHT>\n";
print "<TD BGCOLOR=#000080><IMG SRC=\"../img/kb_logo.gif\" WIDTH=140 HEIGHT=40 ALT=\"Keyboard on-line logo\"></TD>\n";
print "</TR>\n";
print "<TR ALIGN=RIGHT>\n";
print "<TD>\n";
print "<A HREF=\"../../\">СВЕЖИЙ НОМЕР</A>&nbsp;<BR>\n";
print "<A HREF=\"../../archive.htm\">АРХИВ НОМЕРОВ</A>&nbsp;<BR>\n";
print "<A HREF=\"../../\">О СЕРВЕРЕ</A>&nbsp;<BR>\n";
print "ГОСТЕВАЯ&nbsp;<BR>\n";
print "<A HREF=\"../../\">ССЫЛКИ</A>&nbsp;<BR>\n";
print "<A HREF=\"../../\">ЛЮДИ</A>&nbsp;<BR>\n";
print "</TD>\n";
print "</TR>\n";
print "<TR ALIGN=RIGHT>\n";
print "<TD>\n";
print "<BR>\n";
print "<A href=\"http://www.kht.ru/top/\"><img src=\"http://www.kht.ru/top/spider.pl?img=10\" border=0 WIDTH=88 HEIGHT=31 ALT=\"ХТТС TOP\"></A>\n";
print "</TD>\n";
print "</TR>\n";
print "</TABLE>\n";
print "</TD>\n";
print "<!-- end 1st column -->\n";
print "<TD WIDTH=1 BGCOLOR=#000080><IMG SRC=\"../img/pix.gif\" WIDTH=1 HEIGHT=100%></TD>\n";
print "<!-- begin 2nd column -->\n";
print "<TD WIDTH=449>\n";
print "<TABLE WIDTH=100% CELLPADDING=0 CELLSPACING=4 BORDER=0>\n";
print "<TR>\n";
print "<TD BGCOLOR=#000080 CLASS=\"head\">&nbsp;ГОСТЕВАЯ КНИГА</TD>\n";
print "</TR>\n";
print "<TR>\n";
print "<TD>\n";
print "<form action=\"guest.pl\" method=\"POST\">\n";
print "Ваше имя:<BR><input type=\"text\" size=40 name=\"name\" value=\"\"><BR>\n";
print "E-mail:<BR><input type=\"text\" size=40 name=\"email\" value=\"\"><BR>\n";
print "Домашняя страничка:<BR><input type=\"text\" size=40 name=\"homepage\" value=\"http://\"><BR>\n";
print "Комментарий:<BR><textarea name=\"comment\" rows=6 cols=40></textarea>\n";
print "<P><input type=\"submit\" value=\"Добавить\"><IMG SRC=\"pix.gif\" WIDTH=20 HEIGHT=0><input type=\"reset\" value=\"Очистить\">\n";
print "</form>\n";
print "</TD>\n";
print "</TR>\n";
}

sub add_bottom {
print "</TD>\n";
print "</TR>\n";
print "</TABLE>\n";
print "</TD>\n";
print "<!-- end 2nd column -->\n";
print "</TR>\n";
print "</TABLE>\n";
print "<!-- end content -->\n";
print "<!-- begin bottom -->\n";
print "<TABLE WIDTH=600 CELLPADDING=0 CELLSPACING=0 BORDER=0>\n";
print "<TR BGCOLOR=#000080>\n";
print "<TD><IMG SRC=\"../img/pix.gif\" WIDTH=100% HEIGHT=4></TD>\n";
print "</TR>\n";
print "</TABLE>\n";
print "<!-- end bottom -->\n";
print "</BODY>\n";
print "</HTML>\n";
}

sub add_middle {
open(INFILE, "<$origfile");
while ($line = <INFILE>) {
	print $line;
}
close(INFILE);
}
